---
title: Joins and data in the wild
teaching: 30
exercises: 15
questions:
- "How can I change the format of dataframes?"
objectives:
- "To be understand the concepts of 'long' and 'wide' data formats and be able to convert between them with `tidyr`."
keypoints:
- "Use the `tidyr` package to change the layout of dataframes."
- "Use `gather()` to go from wide to long format."
- "Use `spread()` to go from long to wide format."
source: Rmd
---

```{r, include=FALSE}
source("../bin/chunk-options.R")
library(tidyverse)
knitr_fig_path("13-")
# Silently load in the data so the rest of the lesson works
gapminder <- read_csv("data/gapminder-FiveYearData.csv")
```


```{r}
centroids <- read_csv("data/country_centroids_primary.csv")
```
Ah - it's not a CSV. This is why you should look at the data first.  Looks like it might be a tsv..
```{r}
centroids <- read_tsv("data/country_centroids_primary.csv")
```

Column spec looks reasonable - things we'd expect to be numbers are.  Things we'd expect to be character are

## Joining data

We can use `dplyr` to join data.    It looks like we should try and match the `SHORT_NAME` column of the centroids data to the `country` column of the gapminder data.

```{r}
gapcountries <- gapminder %>% select(country, year) %>% filter(year == 2007)

```

```{r}
testjoin <- gapcountries %>% full_join(centroids, by=c("country"="SHORT_NAME"))
```



```{r}
gapcent <- gapminder %>% inner_join(centroids, by=c("country"="SHORT_NAME"))
```

```{r}
 gapminder %>%
  inner_join(centroids, by=c("country"="SHORT_NAME")) %>%
  filter(year==2007) %>%
  ggplot(aes(x=LONG, y=LAT, colour=lifeExp, size=pop)) + geom_point()
```


```{r}
# Olympic medal table - all the loading and cleaning will be done outwith the lesson
# Just get participants to load cleaned version

library(rvest)

medals <- read_html("https://en.wikipedia.org/wiki/2008_Summer_Olympics_medal_table") %>% 
  html_nodes(xpath='//*[@id="mw-content-text"]/div/table[2]') %>% html_table(fill=TRUE)
medals <- medals[[1]]

medals <- medals %>%
  filter(Rank != "Total (87 NOCs)") %>% 
  mutate(country=stringr::str_split(NOC, " \\(", n=1))
```

